# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './../UI/main.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from src.interface import Menu_2

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 1081, 861))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Menu_1 = QtWidgets.QWidget()
        self.Menu_1.setObjectName("Menu_1")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Menu_1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 70, 451, 223))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.Menu_1)
        self.tableWidget.setGeometry(QtCore.QRect(30, 440, 1001, 341))
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(20)
        self.tableWidget.setObjectName("tableWidget")
        self.tabWidget.addTab(self.Menu_1, "")
        self.Menu_2 = QtWidgets.QWidget()
        self.Menu_2.setObjectName("Menu_2")
        self.frame = QtWidgets.QFrame(self.Menu_2)
        self.frame.setGeometry(QtCore.QRect(10, 20, 1041, 771))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 19, 471, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Menu_2_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Menu_2_label.setObjectName("Menu_2_label")
        self.verticalLayout.addWidget(self.Menu_2_label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.Menu_2_textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.Menu_2_textEdit.setObjectName("Menu_2_textEdit")
        self.verticalLayout.addWidget(self.Menu_2_textEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.Menu_2_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Menu_2_button.setObjectName("Menu_2_button")
        self.verticalLayout.addWidget(self.Menu_2_button)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 399, 1001, 361))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Menu_2_tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget_3)
        self.Menu_2_tableWidget.setRowCount(10)
        self.Menu_2_tableWidget.setColumnCount(20)
        self.Menu_2_tableWidget.setObjectName("Menu_2_tableWidget")
        self.gridLayout_3.addWidget(self.Menu_2_tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Menu_2, "")
        self.Menu_3 = QtWidgets.QWidget()
        self.Menu_3.setObjectName("Menu_3")
        self.tabWidget.addTab(self.Menu_3, "")
        self.Menu_4 = QtWidgets.QWidget()
        self.Menu_4.setObjectName("Menu_4")
        self.tabWidget.addTab(self.Menu_4, "")
        self.Menu_5 = QtWidgets.QWidget()
        self.Menu_5.setObjectName("Menu_5")
        self.tabWidget.addTab(self.Menu_5, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayoutWidget.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Menu_2_button.clicked.connect(self.Menu_2_handler)

    def Menu_2_handler(self):
        Menu_2.menu_2(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spin Bike Gardens"))
        self.pushButton.setText(_translate("MainWindow", "Find"))
        self.label.setText(_translate("MainWindow", "Email of Bike Manager"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Menu_1), _translate("MainWindow", "Menu_1"))
        self.Menu_2_label.setText(_translate("MainWindow", "Email of Bike Manager"))
        self.Menu_2_button.setText(_translate("MainWindow", "Find"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Menu_2), _translate("MainWindow", "Menu_2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Menu_3), _translate("MainWindow", "Menu_3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Menu_4), _translate("MainWindow", "Menu_4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Menu_5), _translate("MainWindow", "Menu_5"))

